// @generated by Cratis. Source: CratisApp.ShiftManagement.Scheduling.ShiftAssignments.ShiftAssignments, CratisApp.ShiftManagement.Scheduling.ShiftAssignments.ShiftAssignments. Time: 2026-09-21T14:10:31.9678814Z. Hash: 6EF048BF8FEFAB9AE6EBA5DA2394872182B4F88CD4E8F1523DEC99E4CB7CB92F
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { QueryFor, QueryResultWithState } from '@cratis/arc/queries';
import { useQuery, useSuspenseQuery, PerformQuery, SetSorting, QueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { Guid, field } from '@cratis/fundamentals';

export interface GetShiftAssignmentsParameters {
    shiftId: Guid;
}


export class GetShiftAssignments extends QueryFor<ShiftAssignments, GetShiftAssignmentsParameters> {
    readonly route: string = '/api/shift-management/scheduling/shift-assignments/get-shift-assignments';
    readonly queryName: string = 'CratisApp.ShiftManagement.Scheduling.ShiftAssignments.ShiftAssignments.GetShiftAssignments';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: ShiftAssignments = {} as ShiftAssignments;

    constructor() {
        super(ShiftAssignments, false);
    }

    get requiredRequestParameters(): string[] {
        return [
            'shiftId',
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
        new ParameterDescriptor('shiftId', Guid, false),
    ];

    shiftId!: Guid;


    static use(args?: GetShiftAssignmentsParameters): [QueryResultWithState<ShiftAssignments>, PerformQuery<GetShiftAssignmentsParameters>, SetSorting] {
        return useQuery<ShiftAssignments, GetShiftAssignments, GetShiftAssignmentsParameters>(GetShiftAssignments, args);
    }

    static useSuspense(args?: GetShiftAssignmentsParameters): [QueryResultWithState<ShiftAssignments>, PerformQuery<GetShiftAssignmentsParameters>, SetSorting] {
        return useSuspenseQuery<ShiftAssignments, GetShiftAssignments, GetShiftAssignmentsParameters>(GetShiftAssignments, args);
    }

    static when(condition: boolean): QueryWhen<GetShiftAssignments, ShiftAssignments, GetShiftAssignmentsParameters> {
        return new QueryWhen<GetShiftAssignments, ShiftAssignments, GetShiftAssignmentsParameters>(GetShiftAssignments, condition);
    }
}

export class ShiftAssignments {
    @field(Guid)
    shiftId!: Guid;
    @field(Guid, true)
    employeeIds!: Guid[];
}
