// @generated by Cratis. Source: CratisApp.ShiftManagement.Scheduling.ActiveShiftDetails.ActiveShiftDetails, CratisApp.ShiftManagement.Scheduling.ActiveShiftDetails.ActiveShiftDetails. Time: 2026-09-21T14:04:24.6723961Z. Hash: 1C48B3DB0EABD5DA4C42DA7ECD0AFF3AB684704C8BD90700171691A4E4862E27
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { QueryFor, QueryResultWithState } from '@cratis/arc/queries';
import { useQuery, useSuspenseQuery, PerformQuery, SetSorting, QueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { Guid, field } from '@cratis/fundamentals';

export interface GetActiveShiftDetailsParameters {
    shiftId: Guid;
}


export class GetActiveShiftDetails extends QueryFor<ActiveShiftDetails, GetActiveShiftDetailsParameters> {
    readonly route: string = '/api/shift-management/scheduling/active-shift-details/get-active-shift-details';
    readonly queryName: string = 'CratisApp.ShiftManagement.Scheduling.ActiveShiftDetails.ActiveShiftDetails.GetActiveShiftDetails';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: ActiveShiftDetails = {} as ActiveShiftDetails;

    constructor() {
        super(ActiveShiftDetails, false);
    }

    get requiredRequestParameters(): string[] {
        return [
            'shiftId',
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
        new ParameterDescriptor('shiftId', Guid, false),
    ];

    shiftId!: Guid;


    static use(args?: GetActiveShiftDetailsParameters): [QueryResultWithState<ActiveShiftDetails>, PerformQuery<GetActiveShiftDetailsParameters>, SetSorting] {
        return useQuery<ActiveShiftDetails, GetActiveShiftDetails, GetActiveShiftDetailsParameters>(GetActiveShiftDetails, args);
    }

    static useSuspense(args?: GetActiveShiftDetailsParameters): [QueryResultWithState<ActiveShiftDetails>, PerformQuery<GetActiveShiftDetailsParameters>, SetSorting] {
        return useSuspenseQuery<ActiveShiftDetails, GetActiveShiftDetails, GetActiveShiftDetailsParameters>(GetActiveShiftDetails, args);
    }

    static when(condition: boolean): QueryWhen<GetActiveShiftDetails, ActiveShiftDetails, GetActiveShiftDetailsParameters> {
        return new QueryWhen<GetActiveShiftDetails, ActiveShiftDetails, GetActiveShiftDetailsParameters>(GetActiveShiftDetails, condition);
    }
}

export class ActiveShiftDetails {
    @field(Guid)
    shiftId!: Guid;
    @field(String)
    name!: string;
    @field(String)
    type!: string;
    @field(Boolean)
    recurring!: boolean;
    @field(String)
    fromDay!: string;
    @field(String)
    toDay!: string;
    @field(Date)
    startDateTime!: Date;
    @field(Date)
    endDateTime!: Date;
}
