// @generated - This file is automatically generated by the Cratis proxy generator. Do not edit manually.

/* eslint-disable sort-imports */
import { ObservableQueryFor, QueryResultWithState, Sorting, Paging } from '@cratis/arc/queries';
import { useObservableQuery, useObservableQueryWithPaging, SetSorting, SetPage, SetPageSize } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { Listing } from './Listing';

class AllListingsSortBy {
    constructor(readonly query: AllListings) {}
}

class AllListingsSortByWithoutQuery {}

export class AllListings extends ObservableQueryFor<Listing[]> {
    readonly route: string = '/api/some-module/some-feature/listing/all-listings';
    readonly defaultValue: Listing[] = [];
    private readonly _sortBy: AllListingsSortBy;
    private static readonly _sortBy: AllListingsSortByWithoutQuery = new AllListingsSortByWithoutQuery();

    constructor() {
        super(Listing, true);
        this._sortBy = new AllListingsSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [];

    get sortBy(): AllListingsSortBy {
        return this._sortBy;
    }

    static get sortBy(): AllListingsSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<Listing[]>, SetSorting] {
        return useObservableQuery<Listing[], AllListings>(AllListings, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<Listing[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<Listing[], AllListings>(AllListings, new Paging(0, pageSize), undefined, sorting);
    }
}
