// @generated - This file is automatically generated by the Cratis proxy generator. Do not edit manually.

/* eslint-disable sort-imports */
import { field } from '@cratis/fundamentals';

export class Listing {
    @field(String)
    name!: string;

    @field(String)
    eventSourceId!: string;
}
