// @generated by Cratis. Source: CratisApp.Reservations.Booking.PlaceReservation.PlaceReservation, CratisApp.Reservations.Booking.PlaceReservation.ReservationPlaced. Time: 2026-09-17T18:38:48.7799256Z. Hash: 57ECEA9BD8903419853D470F66A1C9D0918A231F15526BA5510DDE9B290AA650
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { Guid, field } from '@cratis/fundamentals';

export interface IPlaceReservation {
    email?: string;
    end?: Date;
    id?: Guid;
    partySize?: number;
    restaurantId?: Guid;
    start?: Date;
}

export class PlaceReservationValidator extends CommandValidator<IPlaceReservation> {
    constructor() {
        super();
        this.ruleFor(c => c.email).notEmpty().withMessage('Email is required');
        this.ruleFor(c => c.partySize).greaterThanOrEqual(1).withMessage('At least 1 person is required');
    }
}

export class PlaceReservation extends Command<IPlaceReservation, ReservationPlaced> implements IPlaceReservation {
    readonly route: string = '/api/reservations/booking/place-reservation';
    readonly validation: CommandValidator = new PlaceReservationValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('email', String, false),
        new PropertyDescriptor('end', Date, false),
        new PropertyDescriptor('id', Guid, false),
        new PropertyDescriptor('partySize', Number, false),
        new PropertyDescriptor('restaurantId', Guid, false),
        new PropertyDescriptor('start', Date, false),
    ];

    private _email!: string;
    private _end!: Date;
    private _id!: Guid;
    private _partySize!: number;
    private _restaurantId!: Guid;
    private _start!: Date;

    constructor() {
        super(ReservationPlaced, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get email(): string {
        return this._email;
    }

    set email(value: string) {
        this._email = value;
        this.propertyChanged('email');
    }
    get end(): Date {
        return this._end;
    }

    set end(value: Date) {
        this._end = value;
        this.propertyChanged('end');
    }
    get id(): Guid {
        return this._id;
    }

    set id(value: Guid) {
        this._id = value;
        this.propertyChanged('id');
    }
    get partySize(): number {
        return this._partySize;
    }

    set partySize(value: number) {
        this._partySize = value;
        this.propertyChanged('partySize');
    }
    get restaurantId(): Guid {
        return this._restaurantId;
    }

    set restaurantId(value: Guid) {
        this._restaurantId = value;
        this.propertyChanged('restaurantId');
    }
    get start(): Date {
        return this._start;
    }

    set start(value: Date) {
        this._start = value;
        this.propertyChanged('start');
    }

    static use(initialValues?: IPlaceReservation): [PlaceReservation, SetCommandValues<IPlaceReservation>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<PlaceReservation, IPlaceReservation>(PlaceReservation, initialValues);
    }
}

export class ReservationPlaced {
    @field(Guid)
    id!: Guid;
    @field(Guid)
    restaurantId!: Guid;
    @field(String)
    email!: string;
    @field(Date)
    start!: Date;
    @field(Date)
    end!: Date;
    @field(Number)
    partySize!: number;
    @field(String)
    code!: string;
}
