// @generated by Cratis. Source: CratisApp.ShiftManagement.Scheduling.ShiftSummary.ShiftSummary, CratisApp.ShiftManagement.Scheduling.ShiftSummary.ShiftSummary. Time: 2026-09-21T13:45:42.3390239Z. Hash: 480F6FA8F5D12176C8B778E3D1D8F35573B0FE88C26BFF35E2860955E4434386
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { QueryFor, QueryResultWithState } from '@cratis/arc/queries';
import { useQuery, useSuspenseQuery, PerformQuery, SetSorting, QueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { Guid, field } from '@cratis/fundamentals';

export interface GetShiftSummaryParameters {
    shiftId: Guid;
}


export class GetShiftSummary extends QueryFor<ShiftSummary, GetShiftSummaryParameters> {
    readonly route: string = '/api/shift-management/scheduling/shift-summary/get-shift-summary';
    readonly queryName: string = 'CratisApp.ShiftManagement.Scheduling.ShiftSummary.ShiftSummary.GetShiftSummary';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: ShiftSummary = {} as ShiftSummary;

    constructor() {
        super(ShiftSummary, false);
    }

    get requiredRequestParameters(): string[] {
        return [
            'shiftId',
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
        new ParameterDescriptor('shiftId', Guid, false),
    ];

    shiftId!: Guid;


    static use(args?: GetShiftSummaryParameters): [QueryResultWithState<ShiftSummary>, PerformQuery<GetShiftSummaryParameters>, SetSorting] {
        return useQuery<ShiftSummary, GetShiftSummary, GetShiftSummaryParameters>(GetShiftSummary, args);
    }

    static useSuspense(args?: GetShiftSummaryParameters): [QueryResultWithState<ShiftSummary>, PerformQuery<GetShiftSummaryParameters>, SetSorting] {
        return useSuspenseQuery<ShiftSummary, GetShiftSummary, GetShiftSummaryParameters>(GetShiftSummary, args);
    }

    static when(condition: boolean): QueryWhen<GetShiftSummary, ShiftSummary, GetShiftSummaryParameters> {
        return new QueryWhen<GetShiftSummary, ShiftSummary, GetShiftSummaryParameters>(GetShiftSummary, condition);
    }
}

export class ShiftSummary {
    @field(Guid)
    shiftId!: Guid;
    @field(String)
    name!: string;
    @field(String)
    type!: string;
    @field(Date)
    startDateTime!: Date;
    @field(Date)
    endDateTime!: Date;
}
