// @generated by Cratis. Source: CratisApp.ShiftManagement.Scheduling.CreateShift.CreateShift. Time: 2026-09-21T13:27:41.0429538Z. Hash: 0686A02857E2F1E1F07BE89C89424E0EA130D741DFD506BE2FBC5660CCC7529C
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { Guid } from '@cratis/fundamentals';

export interface ICreateShift {
    endDateTime?: Date;
    fromDay?: string;
    name?: string;
    recurring?: boolean;
    startDateTime?: Date;
    toDay?: string;
    type?: string;
}


export class CreateShift extends Command<ICreateShift, Guid> implements ICreateShift {
    readonly route: string = '/api/shift-management/scheduling/create-shift';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('endDateTime', Date, false),
        new PropertyDescriptor('fromDay', String, false),
        new PropertyDescriptor('name', String, false),
        new PropertyDescriptor('recurring', Boolean, false),
        new PropertyDescriptor('startDateTime', Date, false),
        new PropertyDescriptor('toDay', String, false),
        new PropertyDescriptor('type', String, false),
    ];

    private _endDateTime!: Date;
    private _fromDay!: string;
    private _name!: string;
    private _recurring!: boolean;
    private _startDateTime!: Date;
    private _toDay!: string;
    private _type!: string;

    constructor() {
        super(Guid, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get endDateTime(): Date {
        return this._endDateTime;
    }

    set endDateTime(value: Date) {
        this._endDateTime = value;
        this.propertyChanged('endDateTime');
    }
    get fromDay(): string {
        return this._fromDay;
    }

    set fromDay(value: string) {
        this._fromDay = value;
        this.propertyChanged('fromDay');
    }
    get name(): string {
        return this._name;
    }

    set name(value: string) {
        this._name = value;
        this.propertyChanged('name');
    }
    get recurring(): boolean {
        return this._recurring;
    }

    set recurring(value: boolean) {
        this._recurring = value;
        this.propertyChanged('recurring');
    }
    get startDateTime(): Date {
        return this._startDateTime;
    }

    set startDateTime(value: Date) {
        this._startDateTime = value;
        this.propertyChanged('startDateTime');
    }
    get toDay(): string {
        return this._toDay;
    }

    set toDay(value: string) {
        this._toDay = value;
        this.propertyChanged('toDay');
    }
    get type(): string {
        return this._type;
    }

    set type(value: string) {
        this._type = value;
        this.propertyChanged('type');
    }

    static use(initialValues?: ICreateShift): [CreateShift, SetCommandValues<ICreateShift>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<CreateShift, ICreateShift>(CreateShift, initialValues);
    }
}
