// @generated by Cratis. Source: CratisApp.ShiftManagement.Scheduling.AssignEmployeeToShift.AssignEmployeeToShift, CratisApp.ShiftManagement.Scheduling.AssignEmployeeToShift.EmployeeAssignedToShift. Time: 2026-09-21T13:52:17.9798011Z. Hash: C97FA5519C3792E3611F33033495B25371FE7CDE08FCDD90541A6263396206F8
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { Guid, field } from '@cratis/fundamentals';

export interface IAssignEmployeeToShift {
    employeeId?: Guid;
    shiftId?: Guid;
}


export class AssignEmployeeToShift extends Command<IAssignEmployeeToShift, EmployeeAssignedToShift> implements IAssignEmployeeToShift {
    readonly route: string = '/api/shift-management/scheduling/assign-employee-to-shift';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('employeeId', Guid, false),
        new PropertyDescriptor('shiftId', Guid, false),
    ];

    private _employeeId!: Guid;
    private _shiftId!: Guid;

    constructor() {
        super(EmployeeAssignedToShift, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get employeeId(): Guid {
        return this._employeeId;
    }

    set employeeId(value: Guid) {
        this._employeeId = value;
        this.propertyChanged('employeeId');
    }
    get shiftId(): Guid {
        return this._shiftId;
    }

    set shiftId(value: Guid) {
        this._shiftId = value;
        this.propertyChanged('shiftId');
    }

    static use(initialValues?: IAssignEmployeeToShift): [AssignEmployeeToShift, SetCommandValues<IAssignEmployeeToShift>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<AssignEmployeeToShift, IAssignEmployeeToShift>(AssignEmployeeToShift, initialValues);
    }
}

export class EmployeeAssignedToShift {
    @field(Guid)
    shiftId!: Guid;
    @field(Guid)
    employeeId!: Guid;
}
