// @generated - This file is automatically generated by the Cratis proxy generator. Do not edit manually.

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { Guid } from '@cratis/fundamentals';

export interface IRegister {
    name?: string;
}

export class RegisterValidator extends CommandValidator<IRegister> {
    constructor() {
        super();
    }
}

export class Register extends Command<IRegister, Guid> implements IRegister {
    readonly route: string = '/api/some-module/some-feature/registration';
    readonly validation: CommandValidator = new RegisterValidator();
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('name', String, false),
    ];

    private _name!: string;

    constructor() {
        super(Guid, false);
    }

    get requestParameters(): string[] {
        return [];
    }

    get name(): string {
        return this._name;
    }

    set name(value: string) {
        this._name = value;
        this.propertyChanged('name');
    }

    static use(initialValues?: IRegister): [Register, SetCommandValues<IRegister>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<Register, IRegister>(Register, initialValues);
    }
}
